FROM debian:12-slim

WORKDIR /data
USER root
SHELL ["/bin/bash", "-c"]

# libdbd-mysql-perl is the dependency of pt-online-schema-change
RUN set -ex && \
    apt-get update && apt-get install -y --no-install-recommends \
        python3-minimal python3-pip python3-venv \
        libdbd-mysql-perl \
        mariadb-client \
        git wget curl xz-utils && \
    wget percona.com/get/pt-online-schema-change && chmod +x pt-online-schema-change && mv pt-online-schema-change /usr/local/bin/ && \
    apt-get -y auto-remove && rm -rf /var/lib/apt/lists/*

# install node.js from https://github.com/nodejs/docker-node/blob/main/20/bookworm-slim/Dockerfile
ENV NODE_VERSION=20.18.3
ENV ARCH=x64
RUN set -ex \
  && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
  && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
  # fix the error: Your cache folder contains root-owned files
  && mkdir /.npm && chown -R 1000:0 "/.npm" \
  && node --version && npm --version

# install skeema
ENV SKEEMA_VERSION=1.12.3
RUN mkdir skeema && cd skeema && \
    curl -L https://github.com/skeema/skeema/releases/download/v${SKEEMA_VERSION}/skeema_${SKEEMA_VERSION}_linux_amd64.tar.gz | tar xz && \
    mv skeema /usr/local/bin/skeema && \
    cd .. && rm -rf skeema && skeema --version

CMD ["/bin/bash"]
