FROM beim/schema-data-migration:base-0.1.0

RUN apt-get update && apt-get install -y --no-install-recommends python3-dev default-libmysqlclient-dev build-essential pkg-config

RUN mkdir -p /data/schema-data-migration
COPY . /data/schema-data-migration/

RUN set -ex && \
    cd /data/schema-data-migration && ls -alh && python3 -m venv venv && source venv/bin/activate && \
    pip install . && ln -s /data/schema-data-migration/venv/bin/sdm /usr/local/bin/sdm && \
    which sdm

ENV VIRTUAL_ENV /data/schema-data-migration/venv
ENV PATH /data/schema-data-migration/venv/bin:$PATH

WORKDIR /workspace

CMD ["/bin/bash"]
