TEST_TYPE_SIMPLE_FORWARD = "simple_forward"
TEST_TYPE_STEP_FORWARD = "step_forward"
TEST_TYPE_STEP_BACKWARD = "step_backward"
TEST_TYPE_MONKEY = "monkey"
TEST_TYPE_CUSTOM = "custom"
ALL_TEST_TYPE = [
    TEST_TYPE_SIMPLE_FORWARD,
    TEST_TYPE_STEP_FORWARD,
    TEST_TYPE_STEP_BACKWARD,
    TEST_TYPE_MONKEY,
    TEST_TYPE_CUSTOM,
]
ALL_GEN_TEST_TYPE = ALL_TEST_TYPE[:-1]  # Remove the custom
