name: Unittest

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    container: beim/schema-data-migration:base-0.3.0
    strategy:
      matrix:
        dbimage: ['mysql:5.7', 'mysql:8.0', 'mysql:latest', 'mariadb:10', 'mariadb:latest']

    services:
      db1:
        image: ${{ matrix.dbimage }}
        env:
          MYSQL_ROOT_PASSWORD: root
      db2:
        image: ${{ matrix.dbimage }}
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cat /etc/os-release
        python3 --version
        npm --version
        apt-get update && apt-get install -y --no-install-recommends python3-dev default-libmysqlclient-dev build-essential pkg-config git
    
    - name: Run unittest
      shell: bash
      run: |
        python3 -m venv venv && source venv/bin/activate
        pip install -e .[testing]
        python -m pytest --cov=migration --cov-config=.coveragerc ./tests
        git config --global --add safe.directory /__w/schema-data-migration/schema-data-migration
        python -m coveralls --service=github
      env:
        MYSQL_PWD: root
        MIGRATION_CWD: ./cwd
        ALLOW_UNSAFE: 1
        UNITTEST_MYSQL_HOST1: db1
        UNITTEST_MYSQL_PORT1: 3306
        UNITTEST_MYSQL_HOST2: db2
        UNITTEST_MYSQL_PORT2: 3306
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: unittest
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v3

    - name: Build image
      run: |
        docker build -t beim/schema-data-migration:${GITHUB_REF#refs/tags/} .
        docker build -t beim/schema-data-migration:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: |
        docker push beim/schema-data-migration --all-tags
